# Generated by Django 4.2.7 on 2023-11-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=100)),
                ('pot_size', models.IntegerField()),
                ('n', models.CharField(max_length=50)),
                ('p', models.CharField(max_length=50)),
                ('k', models.CharField(max_length=50)),
                ('co2', models.CharField(max_length=50)),
                ('ph', models.CharField(max_length=50)),
                ('ec', models.CharField(max_length=50)),
                ('moisture', models.CharField(max_length=50)),
                ('humidity', models.CharField(max_length=50)),
                ('temperature', models.CharField(max_length=50)),
                ('soil_type', models.CharField(max_length=50)),
                ('rainfall', models.CharField(max_length=50)),
                ('sunlight', models.CharField(max_length=50)),
                ('sunlight_type', models.CharField(max_length=50)),
                ('season', models.CharField(max_length=50)),
                ('watering', models.CharField(max_length=50)),
                ('plant_type', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['plant_name'],
            },
        ),
    ]
