# Generated by Django 4.2.6 on 2023-12-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='plant_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='plant_image',
            field=models.ImageField(null=True, upload_to='plants/'),
        ),
    ]
